version: "2.0"
services:
  mining:
    image: swanchain254/zil_mainnet_f2pool:latest
    env:
      - MINER_URL=stratum+tcp://etc-zil.f2pool.com:6200
      - ACCOUNTNAME=rootabc
      - WORKERNAME=work-001
    expose:
      - port: 5000
        as: 5000
deployment:
  mining:
    lagrange:
      count: 1
