version: "2.0"
services:
  mining:
    image: swanchain254/rvn_mainnet_f2pool:latest
    env:
      - MINER_URL=stratum+tcp://raven.f2pool.com:3636 
      - ACCOUNTNAME=rootabc
      - WORKNAME=work-001
    expose:
      - port: 5000
        as: 5000
deployment:
  mining:
    lagrange:
      count: 1
