version: "2.0"
services:
  mining:
    image: swanchain254/iron_mainnet_f2pool:latest
    env:
      - MINER_URL=stratum+tcp://iron-na.f2pool.com:1500 
      - ACCOUNTNAME=rootabc
      - WORKERNAME=work-001
    expose:
      - port: 5000
        as: 5000
deployment:
  mining:
    lagrange:
      count: 1
