version: "2.0"

type: node-port
services:
  vm:
    image: alex6nbai/ubuntu-22.04:cuda-12_1
    # command:
    #   - /usr/local/bin/entrypoint.sh
    # args:
    #   - --host
    #   - 0.0.0.0
    #   - --port
    #   - 9099
    #   - --model
    #   - Qwen/Qwen3-4B-Instruct-2507
    env:
      - sshkey=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZFarrQJ38edLKPS83BzoALPHy3xtZKF5/947lDDCBIMRRrA+NiTmwmITGBmhacDoYWWhpzuRrHzNjFRGfCrTeX4NrZ9/lXYmS5rdYjjzPexh2gtMFLMYeGRwJDsAs+Wbj/qfzZzdw5PMUsoy9cSx5pRQKIjTJ7yUoNDeJ1HkacpImZk7pSeDZhWJnweCjABBkJ3N7dnVOUtHL5YWxLr8PVC8HS1QEg6qY5k41hcvdd9fNb2fewgaKnIHOBR10mX7c9s8+wihY6iw2rHf7hMC2AZZqpYzk9v0pc0AXuIBCqoXmRWC1GA1i/BOF+o1mwNz/RYtznziK276ZyjrC30d/UUSUcZ4FcotNf6pvhmCFXZMKUHGN0B/5UB91CmUJqBRlZUiVbFc1xQjf9xxTkWaJvr5Rnan0qyreOnT+aH+ZH1sZ/+P6U318G2l+T9bddWu1NfzoDSZ4TDXGpPPtQ1KHqlahkas5Z/I77d4Si56kIw108kklbx1DxxMuwEr0hv0= alexchen@YONGs-MBP
      - username=alex
    expose:
      - port: 8000
        as: 80
        proto: http
      - port: 22

deployment:
  vm:
    lagrange:
      count: 1 
