version: "2.0"
services:
  mining:
    image: swanchain254/alph_mainnet_f2pool:latest
    env:
      - MINER_URL=stratum+tcp://alph-asia.f2pool.com:5600
      - ACCOUNTNAME=rootabc
      - WORKERNAME=work-001
    expose:
      - port: 5000
        as: 5000
deployment:
  mining:
    lagrange:
      count: 1
