#binance
version: "2.0"
services:
  mining:
    image: swanchain254/ethw_mainnet_binance:latest
    env:
    - MINER_URL=stratum+tcp://ethw.poolbinance.com:443
    - ACCOUNTNAME=rootabc
    - WORKERNAME=work-001
    expose:
      - port: 5000
        as: 5000
deployment:
  mining:
    lagrange:
      count: 1
