#h9pool
version: "2.0"
services:
  mining:
    image: swanchain254/aleo_mainnet_h9:2.1.3
    env:
      - APIKEY=<YOUR_API_KEY>
      - WORKERNAME=work-001
    expose:
      - port: 5000
        as: 5000
deployment:
  mining:
    lagrange:
      count: 1
