version: "2.0"

services:
  vllmcontainer: 
    image: alex6nbai/nb_vllm:vllm-latest-20250819-2
    env:
      - MODEL_NAME=huihui-ai/Huihui-gpt-oss-20b-BF16-abliterated
      - NCCL_DEBUG=INFO

    expose:
      - port: 80
        as: 80 

deployment:
  vllmcontainer:
    lagrange:
      count: 1 
