version: "2.0"

services:
  vllmcontainer: 
    image: alex6nbai/nb_vllm:20250814-6
    env:
      - MODEL_NAME=Valdemardi/DeepSeek-R1-Distill-Llama-70B-AWQ

    expose:
      - port: 80
        as: 80 

deployment:
  vllmcontainer:
    lagrange:
      count: 1 
